server:
  port: 8082

spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

