server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.example.userservice: DEBUG
  file:
    name: logs/user-service.log
    max-size: 10MB
    max-history: 30
