server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passenger_service
    username: root
    password: Avinash@12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.yourapp: DEBUG
    com.job.portal.service: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 30

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka