#
#server:
#  port: 8090
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/email_service
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: gidijalachaitanya733@gmail.com
#    password: vmpn gagb gucy snzi
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#logging:
#  level:
#    root: INFO
#    com.school.studentservice: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  file:
#    name: logs/email-service.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"